import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Posts | What Next",
  description: "Generated by create next app",
};

const getPost = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();
  return data;
};

const Postspage = async () => {
  const allPost = await getPost();
  // console.log(allPost);

  return (
    <div>
      <div className="grid grid-cols-4 gap-4 m-4">
        {allPost?.slice(0, 10).map((post) => (
          <div key={post.id} className="border-2 rounded-md p-3   bg-red-200 ">
            <h2 className="font-semibold text-xl uppercase">{post.title}</h2>
            <p>{post.body}</p>
            <Link href={`/posts/${post.id}`}>
              <button className="bg-amber-300 p-3 rounded-md">Read More</button>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Postspage;
